# =================================================================
# Stationly Syncer - Remote Environment Overrides
# =================================================================

# TfL API Configuration
tfl.app.key=

# Firebase & Firestore Configuration
firestore.project-id=
